// Generated by CoffeeScript 2.3.1
(function() {
  var activate, deactivate, fmt, root, vscode;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  vscode = require("vscode");

  fmt = require("coffee-fmt");

  activate = function(context) {
    var disposable;
    disposable = vscode.commands.registerCommand('extension.formatIt', function() {
      var coffee, config, doc, editor;
      editor = vscode.window.activeTextEditor;
      doc = editor != null ? editor.document : void 0;
      config = vscode.workspace.getConfiguration("myCoffeeScriptFormatter");
      coffee = fmt.format(doc != null ? doc.getText() : void 0, {
        "tab": config.indentation
      });
      return editor.edit(function(e) {
        var end, range, start;
        start = new vscode.Position(0, 0);
        end = new vscode.Position((doc != null ? doc.lineCount : void 0) - 1, doc.lineAt(doc.lineCount - 1).text.length);
        range = new vscode.Range(start, end);
        return e.replace(range, coffee);
      }).then(function(r) {
        var postion;
        postion = editor.selection.end;
        return editor.selection = new vscode.Selection(postion, postion);
      });
    });
    return context.subscriptions.push(disposable);
  };

  exports.activate = activate;

  deactivate = function() {};

  exports.deactivate = deactivate;

}).call(this);
